[包]
格式 = 2
名称 = "yanxu-platform"
版本 = "0.9.0"
言序 = ">=1.1.7, <2.0.0"
入口 = "src/主.yx"
说明 = "言序原生跨平台平台接口库"
许可 = "MIT OR Apache-2.0"

[导出]
默认 = "src/主.yx"

[权限]
图形界面 = true
原生扩展 = true
剪贴板 = true
文件对话框 = true

[原生]
ABI = 2

# scripts/prepare-current.sh 在此后追加当前平台的制品、摘要与大小。
[原生.linux.x64]
文件 = "dist/x86_64-unknown-linux-gnu/libyanxu_platform_native.so"
校验和 = "4d321de2e9176c0db73f0f1f7f5e44b6da1e648c379cb1d7bf9e81bc3bebcf4a"
大小 = 15304480
[原生.linux.arm64]
文件 = "dist/aarch64-unknown-linux-gnu/libyanxu_platform_native.so"
校验和 = "75f14e39003d06fd1e8c25244ebdb1ce28801c761d3aaf9c7a9ce7a166600a1d"
大小 = 14553968
[原生.macos.x64]
文件 = "dist/x86_64-apple-darwin/libyanxu_platform_native.dylib"
校验和 = "96f604c01981e7cdbec5e79e7bfa6b4f806b87b6d79e391d29d6a2f0c03014bd"
大小 = 6524288
[原生.macos.arm64]
文件 = "dist/aarch64-apple-darwin/libyanxu_platform_native.dylib"
校验和 = "12859a10f5e24b402b481d890f5dafaa8ba1be71b8f99a3366037042f8ea3bf4"
大小 = 6129760
[原生.windows.x64]
文件 = "dist/x86_64-pc-windows-msvc/yanxu_platform_native.dll"
校验和 = "8ce2ea3f6f09f7c45129207c1fbb6b3cc272b2dd7e1d5e8686b805d12fe18859"
大小 = 4951552
[原生.windows.arm64]
文件 = "dist/aarch64-pc-windows-msvc/yanxu_platform_native.dll"
校验和 = "d624758e1ca47f589168ca8fdbe2f14bb4f0b9d2d98bb29e06a13de168db5973"
大小 = 4255232
